//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DCAAnalyzerServiceWeb.DCAAnalyzerService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DCAAnalyzerServiceSoap", Namespace="http://tempuri.org/")]
    public partial class DCAAnalyzerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CalculateInitialInvestmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalculateSharesPurchasedOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalculateCurrentInvestmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalculateAverageCostOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalculateReturnsDCAOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalculateReturnsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalculateReturnsPercentageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DCAAnalyzerService() {
            this.Url = global::DCAAnalyzerServiceWeb.Properties.Settings.Default.DCAAnalyzerServiceWeb_DCAAnalyzerService_DCAAnalyzerService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CalculateInitialInvestmentCompletedEventHandler CalculateInitialInvestmentCompleted;
        
        /// <remarks/>
        public event CalculateSharesPurchasedCompletedEventHandler CalculateSharesPurchasedCompleted;
        
        /// <remarks/>
        public event CalculateCurrentInvestmentCompletedEventHandler CalculateCurrentInvestmentCompleted;
        
        /// <remarks/>
        public event CalculateAverageCostCompletedEventHandler CalculateAverageCostCompleted;
        
        /// <remarks/>
        public event CalculateReturnsDCACompletedEventHandler CalculateReturnsDCACompleted;
        
        /// <remarks/>
        public event CalculateReturnsCompletedEventHandler CalculateReturnsCompleted;
        
        /// <remarks/>
        public event CalculateReturnsPercentageCompletedEventHandler CalculateReturnsPercentageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalculateInitialInvestment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double CalculateInitialInvestment(double monthlyDCA, double month) {
            object[] results = this.Invoke("CalculateInitialInvestment", new object[] {
                        monthlyDCA,
                        month});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void CalculateInitialInvestmentAsync(double monthlyDCA, double month) {
            this.CalculateInitialInvestmentAsync(monthlyDCA, month, null);
        }
        
        /// <remarks/>
        public void CalculateInitialInvestmentAsync(double monthlyDCA, double month, object userState) {
            if ((this.CalculateInitialInvestmentOperationCompleted == null)) {
                this.CalculateInitialInvestmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateInitialInvestmentOperationCompleted);
            }
            this.InvokeAsync("CalculateInitialInvestment", new object[] {
                        monthlyDCA,
                        month}, this.CalculateInitialInvestmentOperationCompleted, userState);
        }
        
        private void OnCalculateInitialInvestmentOperationCompleted(object arg) {
            if ((this.CalculateInitialInvestmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateInitialInvestmentCompleted(this, new CalculateInitialInvestmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalculateSharesPurchased", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CalculateSharesPurchased(double monthlyDCA, double price) {
            object[] results = this.Invoke("CalculateSharesPurchased", new object[] {
                        monthlyDCA,
                        price});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CalculateSharesPurchasedAsync(double monthlyDCA, double price) {
            this.CalculateSharesPurchasedAsync(monthlyDCA, price, null);
        }
        
        /// <remarks/>
        public void CalculateSharesPurchasedAsync(double monthlyDCA, double price, object userState) {
            if ((this.CalculateSharesPurchasedOperationCompleted == null)) {
                this.CalculateSharesPurchasedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateSharesPurchasedOperationCompleted);
            }
            this.InvokeAsync("CalculateSharesPurchased", new object[] {
                        monthlyDCA,
                        price}, this.CalculateSharesPurchasedOperationCompleted, userState);
        }
        
        private void OnCalculateSharesPurchasedOperationCompleted(object arg) {
            if ((this.CalculateSharesPurchasedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateSharesPurchasedCompleted(this, new CalculateSharesPurchasedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalculateCurrentInvestment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double CalculateCurrentInvestment(double totalShares, double lastprice) {
            object[] results = this.Invoke("CalculateCurrentInvestment", new object[] {
                        totalShares,
                        lastprice});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void CalculateCurrentInvestmentAsync(double totalShares, double lastprice) {
            this.CalculateCurrentInvestmentAsync(totalShares, lastprice, null);
        }
        
        /// <remarks/>
        public void CalculateCurrentInvestmentAsync(double totalShares, double lastprice, object userState) {
            if ((this.CalculateCurrentInvestmentOperationCompleted == null)) {
                this.CalculateCurrentInvestmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateCurrentInvestmentOperationCompleted);
            }
            this.InvokeAsync("CalculateCurrentInvestment", new object[] {
                        totalShares,
                        lastprice}, this.CalculateCurrentInvestmentOperationCompleted, userState);
        }
        
        private void OnCalculateCurrentInvestmentOperationCompleted(object arg) {
            if ((this.CalculateCurrentInvestmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateCurrentInvestmentCompleted(this, new CalculateCurrentInvestmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalculateAverageCost", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double CalculateAverageCost(double totalInvestment, double totalShares) {
            object[] results = this.Invoke("CalculateAverageCost", new object[] {
                        totalInvestment,
                        totalShares});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void CalculateAverageCostAsync(double totalInvestment, double totalShares) {
            this.CalculateAverageCostAsync(totalInvestment, totalShares, null);
        }
        
        /// <remarks/>
        public void CalculateAverageCostAsync(double totalInvestment, double totalShares, object userState) {
            if ((this.CalculateAverageCostOperationCompleted == null)) {
                this.CalculateAverageCostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateAverageCostOperationCompleted);
            }
            this.InvokeAsync("CalculateAverageCost", new object[] {
                        totalInvestment,
                        totalShares}, this.CalculateAverageCostOperationCompleted, userState);
        }
        
        private void OnCalculateAverageCostOperationCompleted(object arg) {
            if ((this.CalculateAverageCostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateAverageCostCompleted(this, new CalculateAverageCostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalculateReturnsDCA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double CalculateReturnsDCA(double currentInvestment, double monthlyDCA, int month) {
            object[] results = this.Invoke("CalculateReturnsDCA", new object[] {
                        currentInvestment,
                        monthlyDCA,
                        month});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void CalculateReturnsDCAAsync(double currentInvestment, double monthlyDCA, int month) {
            this.CalculateReturnsDCAAsync(currentInvestment, monthlyDCA, month, null);
        }
        
        /// <remarks/>
        public void CalculateReturnsDCAAsync(double currentInvestment, double monthlyDCA, int month, object userState) {
            if ((this.CalculateReturnsDCAOperationCompleted == null)) {
                this.CalculateReturnsDCAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateReturnsDCAOperationCompleted);
            }
            this.InvokeAsync("CalculateReturnsDCA", new object[] {
                        currentInvestment,
                        monthlyDCA,
                        month}, this.CalculateReturnsDCAOperationCompleted, userState);
        }
        
        private void OnCalculateReturnsDCAOperationCompleted(object arg) {
            if ((this.CalculateReturnsDCACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateReturnsDCACompleted(this, new CalculateReturnsDCACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalculateReturns", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double CalculateReturns(double currentInvestment, double initialInvestment) {
            object[] results = this.Invoke("CalculateReturns", new object[] {
                        currentInvestment,
                        initialInvestment});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void CalculateReturnsAsync(double currentInvestment, double initialInvestment) {
            this.CalculateReturnsAsync(currentInvestment, initialInvestment, null);
        }
        
        /// <remarks/>
        public void CalculateReturnsAsync(double currentInvestment, double initialInvestment, object userState) {
            if ((this.CalculateReturnsOperationCompleted == null)) {
                this.CalculateReturnsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateReturnsOperationCompleted);
            }
            this.InvokeAsync("CalculateReturns", new object[] {
                        currentInvestment,
                        initialInvestment}, this.CalculateReturnsOperationCompleted, userState);
        }
        
        private void OnCalculateReturnsOperationCompleted(object arg) {
            if ((this.CalculateReturnsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateReturnsCompleted(this, new CalculateReturnsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalculateReturnsPercentage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double CalculateReturnsPercentage(double returns, double initialInvestment) {
            object[] results = this.Invoke("CalculateReturnsPercentage", new object[] {
                        returns,
                        initialInvestment});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void CalculateReturnsPercentageAsync(double returns, double initialInvestment) {
            this.CalculateReturnsPercentageAsync(returns, initialInvestment, null);
        }
        
        /// <remarks/>
        public void CalculateReturnsPercentageAsync(double returns, double initialInvestment, object userState) {
            if ((this.CalculateReturnsPercentageOperationCompleted == null)) {
                this.CalculateReturnsPercentageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateReturnsPercentageOperationCompleted);
            }
            this.InvokeAsync("CalculateReturnsPercentage", new object[] {
                        returns,
                        initialInvestment}, this.CalculateReturnsPercentageOperationCompleted, userState);
        }
        
        private void OnCalculateReturnsPercentageOperationCompleted(object arg) {
            if ((this.CalculateReturnsPercentageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateReturnsPercentageCompleted(this, new CalculateReturnsPercentageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CalculateInitialInvestmentCompletedEventHandler(object sender, CalculateInitialInvestmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculateInitialInvestmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateInitialInvestmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CalculateSharesPurchasedCompletedEventHandler(object sender, CalculateSharesPurchasedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculateSharesPurchasedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateSharesPurchasedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CalculateCurrentInvestmentCompletedEventHandler(object sender, CalculateCurrentInvestmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculateCurrentInvestmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateCurrentInvestmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CalculateAverageCostCompletedEventHandler(object sender, CalculateAverageCostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculateAverageCostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateAverageCostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CalculateReturnsDCACompletedEventHandler(object sender, CalculateReturnsDCACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculateReturnsDCACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateReturnsDCACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CalculateReturnsCompletedEventHandler(object sender, CalculateReturnsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculateReturnsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateReturnsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CalculateReturnsPercentageCompletedEventHandler(object sender, CalculateReturnsPercentageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculateReturnsPercentageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateReturnsPercentageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591